"""
PDF report generator — 10-section A4 document covering protocol through results.

Sections 1–9 use fpdf2; section 10 (per-paper summaries) uses ReportLab Platypus
because fpdf2 can't wrap text inside table cells. The two halves are merged with pypdf.
An optional PRISMA SVG from the frontend is converted to a vector page via svglib.
"""
from __future__ import annotations

import io
import json
import os
import tempfile
from collections import Counter, defaultdict
from datetime import datetime
from itertools import groupby
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from fpdf import FPDF
from pydantic import BaseModel
from sqlmodel import Session, select

from ..database import get_session
from ..models import (
    ConflictLog, DatabaseSearchString, ExclusionCriterion, ExtractionField,
    ExtractionRecord, FinalDecision, InclusionCriterion, Paper,
    PaperDatabaseLink, Project, QACriterion, QAScore, Reviewer,
    ReviewerDecision, SnowballingIteration, TaxonomyEntry,
)
from ..services.kappa_service import calculate_kappa

router = APIRouter(prefix="/projects", tags=["report"])

# ── Colours ───────────────────────────────────────────────────────────────────
_BLACK   = (0, 0, 0)
_DARK    = (51, 51, 51)
_GRAY    = (107, 114, 128)
_GRAY_LT = (156, 163, 175)
_GRAY_BG = (249, 250, 251)
_TH_BG   = (240, 240, 240)
_BORDER  = (209, 213, 219)
_WHITE   = (255, 255, 255)

_CW = 170.0  # content width mm (A4 - 20mm margins)

_DB_DISPLAY = {
    "acm": "ACM Digital Library", "dblp": "DBLP", "ieee": "IEEE Xplore",
    "scopus": "Elsevier Scopus", "springerlink": "SpringerLink",
    "wiley": "Wiley Online Library",
}
_DB_ALIASES = {
    "springer": "springerlink", "springer link": "springerlink", "springerlink": "springerlink",
    "ieee xplore": "ieee", "ieee explore": "ieee", "ieee": "ieee",
    "scopus": "scopus", "elsevier": "scopus", "elsevier scopus": "scopus",
    "acm": "acm", "acm digital library": "acm",
    "wiley": "wiley", "wiley online library": "wiley",
    "dblp": "dblp", "dblp library": "dblp",
}


def _s(v, maxlen=0):
    """Sanitise a value for fpdf2's latin-1-only text engine.
    Replaces common Unicode chars (curly quotes, em-dash, kappa, etc.) with
    ASCII equivalents, then force-encodes to latin-1 with replacement."""
    if v is None: return "-"
    t = (str(v).replace("\u2026","...").replace("\u2014","-").replace("\u2013","-")
         .replace("|",".").replace("\u00d7","x").replace("\u2019","'").replace("\u2018","'")
         .replace("\u201c",'"').replace("\u201d",'"').replace("\u03ba","k")
         .replace("\u2265",">=").replace("\u2264","<=")
         .encode("latin-1",errors="replace").decode("latin-1"))
    if maxlen and len(t)>maxlen: t=t[:maxlen-3]+"..."
    return t

def _norm_db(r): return _DB_ALIASES.get(r.lower().strip(), r.lower().strip())
def _db_name(c): return _DB_DISPLAY.get(c, c.replace("_"," ").title())


# ─────────────────────────────────────────────────────────────────────────────
class _Report(FPDF):
    """Times-Roman based A4 report with auto-wrapping tables."""

    def __init__(self, title):
        super().__init__("P","mm","A4")
        self.slr_title = _s(title, 80)
        self.set_margins(20,20,20)
        self.set_auto_page_break(True, margin=22)
        self._is_cover = True

    def header(self):
        if self._is_cover: return
        self.set_font("Times","I",7); self.set_text_color(*_GRAY_LT)
        self.cell(0,5,self.slr_title,align="L")
        self.cell(0,5,f"Page {self.page_no()}",align="R")
        self.ln(5)
        self.set_draw_color(*_BORDER); self.set_line_width(0.15)
        self.line(self.l_margin,self.get_y(),self.l_margin+_CW,self.get_y())
        self.ln(3); self.set_text_color(*_BLACK)

    def footer(self):
        if self._is_cover: return
        self.set_y(-12)
        self.set_draw_color(*_BORDER); self.set_line_width(0.15)
        self.line(self.l_margin,self.get_y(),self.l_margin+_CW,self.get_y())
        self.set_font("Times","",6.5); self.set_text_color(*_GRAY_LT)
        self.cell(0,8,f"Generated by ReviQ  .  {self.slr_title}  .  Page {self.page_no()}",align="C")
        self.set_text_color(*_BLACK)

    # ── Headings (4-level hierarchy) ─────────────────────────────────────────

    def section_sep(self):
        """~24pt spacer between sections (replaces forced page break)."""
        self.ln(8.5)

    def h2(self, text):
        """Level 1: Section heading — 13pt bold black, 18pt space before, black rule."""
        if self.get_y() + 25 > self.page_break_trigger: self.add_page()
        self.ln(6.5)  # ~18pt
        self.set_font("Times","B",13); self.set_text_color(*_BLACK)
        self.cell(0,7,_s(text),ln=True)
        y=self.get_y(); self.set_draw_color(*_BLACK); self.set_line_width(0.4)
        self.line(self.l_margin,y,self.l_margin+_CW,y)
        self.set_line_width(0.2); self.ln(2.5)

    def h3(self, text):
        """Level 2: Subsection — 11pt bold #333, 12pt space before, light gray underline."""
        if self.get_y() + 16 > self.page_break_trigger: self.add_page()
        self.ln(4.2)  # ~12pt
        self.set_font("Times","B",11); self.set_text_color(*_DARK)
        self.cell(0,5.5,_s(text),ln=True)
        y=self.get_y(); self.set_draw_color(*_GRAY_LT); self.set_line_width(0.18)
        self.line(self.l_margin,y,self.l_margin+_CW,y)
        self.set_draw_color(*_BLACK); self.set_line_width(0.2)
        self.ln(1.5); self.set_text_color(*_BLACK)

    def h4(self, text):
        """Level 3: Field label — 10pt bold #444, 8pt space before."""
        if self.get_y() + 10 > self.page_break_trigger: self.add_page()
        self.ln(2.8)  # ~8pt
        self.set_font("Times","B",10); self.set_text_color(68,68,68)  # #444
        self.cell(0,4.5,_s(text),ln=True)
        self.set_text_color(*_BLACK)

    def body(self, text):
        """Body text — 9pt regular #333."""
        self.set_x(self.l_margin); self.set_font("Times","",9); self.set_text_color(*_DARK)
        self.multi_cell(_CW,4.5,_s(text)); self.set_text_color(*_BLACK); self.ln(1)

    def note(self, text):
        self.set_x(self.l_margin); self.set_font("Times","I",8); self.set_text_color(*_DARK)
        self.multi_cell(_CW,4,_s(text,600)); self.set_text_color(*_BLACK); self.ln(1)

    def indent_text(self, text, indent=4):
        """Regular-weight indented text — 9pt #333."""
        self.set_x(self.l_margin + indent)
        self.set_font("Times","",9); self.set_text_color(*_DARK)
        self.multi_cell(_CW - indent, 4, _s(text))
        self.set_text_color(*_BLACK); self.ln(0.5)

    def _measure_mc(self, txt, w, font_name="Times", font_style="", font_size=8):
        """Estimate multi-cell height for text in given width."""
        self.set_font(font_name, font_style, font_size)
        line_h = font_size * 0.42
        words = _s(str(txt)).split(" ")
        lines = 1; cur_w = 0
        for word in words:
            ww = self.get_string_width(word + " ")
            if cur_w + ww > w and cur_w > 0: lines += 1; cur_w = ww
            else: cur_w += ww
        return max(lines * line_h, line_h)

    # ── Wrapping table ────────────────────────────────────────────────────────

    def _text_height(self, txt, w, font_name="Times", font_style="", font_size=8):
        """Estimate multi-cell height for text in given width."""
        self.set_font(font_name, font_style, font_size)
        # Use get_string_width to calculate lines needed
        words = _s(txt).split(" ")
        line_h = font_size * 0.45  # approx mm per line
        lines = 1; line_w = 0
        for word in words:
            word_w = self.get_string_width(word + " ")
            if line_w + word_w > w and line_w > 0:
                lines += 1; line_w = word_w
            else:
                line_w += word_w
        return max(lines * line_h, line_h)

    def wrapping_table(self, cols, rows):
        """Table with auto-wrapping cells. cols=[(label, frac), ...], rows=[[str,...],...]"""
        abs_cols = [(_s(label), _CW * frac) for label, frac in cols]
        line_h = 4.0

        # Header
        if self.get_y() + 12 > self.page_break_trigger: self.add_page()
        self.set_font("Times","B",7.5); self.set_fill_color(*_TH_BG)
        self.set_text_color(*_BLACK); self.set_draw_color(*_BORDER)
        for label, w in abs_cols:
            self.cell(w, 5.5, label, border=1, fill=True)
        self.ln(); self.set_fill_color(*_WHITE)

        # Rows
        for ri, row in enumerate(rows):
            # Calculate row height
            max_h = line_h
            for ci, (_, w) in enumerate(abs_cols):
                cell_text = _s(str(row[ci]) if ci < len(row) else "")
                h = self._text_height(cell_text, w - 2)
                if h > max_h: max_h = h
            row_h = max(max_h + 2, line_h + 1)

            if self.get_y() + row_h > self.page_break_trigger: self.add_page()

            fill = ri % 2 == 1
            self.set_fill_color(*(_GRAY_BG if fill else _WHITE))
            self.set_draw_color(*_BORDER)
            x0 = self.get_x(); y0 = self.get_y()

            # Draw cell backgrounds and borders
            for _, w in abs_cols:
                self.rect(self.get_x(), y0, w, row_h, "FD" if fill else "D")
                self.set_x(self.get_x() + w)

            # Render text
            for ci, (_, w) in enumerate(abs_cols):
                cell_text = _s(str(row[ci]) if ci < len(row) else "")
                x = x0 + sum(ww for _, ww in abs_cols[:ci])
                self.set_xy(x + 1, y0 + 0.5)
                self.set_font("Times", "B" if ci == 0 else "", 7.5)
                self.set_text_color(*_BLACK)
                self.multi_cell(w - 2, line_h, cell_text)

            self.set_xy(x0, y0 + row_h)
        self.set_fill_color(*_WHITE); self.ln(2)

    def kv_table(self, rows, label_frac=0.50):
        lw = _CW * label_frac; vw = _CW * (1 - label_frac)
        for i, (label, value) in enumerate(rows):
            # Calculate height
            lh = self._text_height(label, lw - 2)
            vh = self._text_height(value, vw - 2, font_style="B")
            row_h = max(lh + 2, vh + 2, 5.0)

            if self.get_y() + row_h > self.page_break_trigger: self.add_page()

            fill = i % 2 == 1
            self.set_fill_color(*(_GRAY_BG if fill else _WHITE))
            self.set_draw_color(*_BORDER)
            x0 = self.get_x(); y0 = self.get_y()

            self.rect(x0, y0, lw, row_h, "FD" if fill else "D")
            self.rect(x0 + lw, y0, vw, row_h, "FD" if fill else "D")

            self.set_xy(x0 + 1, y0 + 0.5)
            self.set_font("Times","",8); self.set_text_color(*_BLACK)
            self.multi_cell(lw - 2, 4, _s(label))

            self.set_xy(x0 + lw + 1, y0 + 0.5)
            self.set_font("Times","B",8)
            self.multi_cell(vw - 2, 4, _s(value))

            self.set_xy(x0, y0 + row_h)
        self.set_fill_color(*_WHITE); self.ln(2)


class ReportBody(BaseModel):
    prisma_svg: Optional[str] = None


# ─────────────────────────────────────────────────────────────────────────────

def _merge_prisma_pdf(main_pdf_bytes: bytes, prisma_svg: str, insert_after_page: int) -> bytes:
    """Convert SVG to a vector PDF page via svglib/reportlab and merge it into the main PDF."""
    try:
        from svglib.svglib import svg2rlg
        from reportlab.graphics import renderPDF
        from pypdf import PdfReader, PdfWriter
    except ImportError:
        return main_pdf_bytes  # dependencies not available, skip

    # Render SVG to vector PDF
    drawing = svg2rlg(io.BytesIO(prisma_svg.encode("utf-8")))
    if drawing is None:
        return main_pdf_bytes

    # Scale drawing to fit A4 width (170mm ≈ 482pt, at 72 dpi = 482pt)
    target_w = 482.0
    scale = target_w / drawing.width if drawing.width > 0 else 1.0
    drawing.width = target_w
    drawing.height = drawing.height * scale
    drawing.scale(scale, scale)

    prisma_pdf_bytes = renderPDF.drawToString(drawing)

    # Merge
    writer = PdfWriter()
    main_reader = PdfReader(io.BytesIO(main_pdf_bytes))
    prisma_reader = PdfReader(io.BytesIO(prisma_pdf_bytes))

    for i, page in enumerate(main_reader.pages):
        writer.add_page(page)
        if i == insert_after_page - 1 and prisma_reader.pages:
            writer.add_page(prisma_reader.pages[0])

    buf = io.BytesIO()
    writer.write(buf)
    return buf.getvalue()


def _build_section10_pdf(
    included_pap, avg_qa, project, all_fns, fl, rec_map, section_num, slr_title,
):
    """Build Section 10 (Included Papers) as a standalone ReportLab PDF.

    Uses Platypus instead of fpdf2 here because we need text wrapping in table
    cells. Each paper is a KeepTogether block (title + citation table + extraction
    table). Result gets appended to the main PDF via pypdf.
    """
    from reportlab.lib import colors as rl_colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        HRFlowable, KeepTogether,
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20*mm, rightMargin=20*mm,
        topMargin=20*mm, bottomMargin=22*mm,
    )
    avail_w = doc.width  # ~170mm in points

    # Styles
    s_title = ParagraphStyle("PaperTitle", fontName="Times-Bold", fontSize=9,
                             leading=12, textColor=rl_colors.black, spaceAfter=2,
                             leftIndent=0, rightIndent=0)
    s_label = ParagraphStyle("Label", fontName="Times-Bold", fontSize=8,
                             leading=10, textColor=rl_colors.black)
    s_value = ParagraphStyle("Value", fontName="Times-Roman", fontSize=8,
                             leading=10, textColor=rl_colors.Color(0.2, 0.2, 0.2))
    s_heading = ParagraphStyle("SectionHeading", fontName="Times-Bold", fontSize=13,
                               leading=16, textColor=rl_colors.black, spaceAfter=4, spaceBefore=6)
    s_note = ParagraphStyle("Note", fontName="Times-Italic", fontSize=8,
                            leading=10, textColor=rl_colors.Color(0.2, 0.2, 0.2), spaceAfter=8)
    s_footer = ParagraphStyle("Footer", fontName="Times-Roman", fontSize=6.5,
                              leading=8, textColor=rl_colors.Color(0.6, 0.6, 0.6),
                              alignment=1)  # centered

    # Build header/footer for these pages
    title_safe = _s(slr_title, 80)

    def _on_page(canvas, doc):
        canvas.saveState()
        canvas.setFont("Times-Italic", 7)
        canvas.setFillColor(rl_colors.Color(0.6, 0.6, 0.6))
        canvas.drawString(20*mm, A4[1] - 14*mm, title_safe)
        canvas.drawRightString(A4[0] - 20*mm, A4[1] - 14*mm, f"Page {doc.page}")
        canvas.setStrokeColor(rl_colors.Color(0.82, 0.84, 0.86))
        canvas.setLineWidth(0.15*mm)
        canvas.line(20*mm, A4[1] - 15*mm, A4[0] - 20*mm, A4[1] - 15*mm)
        # Footer
        canvas.line(20*mm, 16*mm, A4[0] - 20*mm, 16*mm)
        canvas.setFont("Times-Roman", 6.5)
        canvas.drawCentredString(A4[0]/2, 10*mm,
            f"Generated by ReviQ  .  {title_safe}  .  Page {doc.page}")
        canvas.restoreState()

    story = []

    # Section heading
    story.append(Paragraph(
        f"{section_num}. Included Papers ({len(included_pap)})", s_heading))
    story.append(HRFlowable(width="100%", thickness=0.4*mm,
                             color=rl_colors.black, spaceAfter=3*mm))
    story.append(Paragraph(
        "Full bibliographic details are available in the BibTeX file in the replication package.",
        s_note))

    cit_col_w = [avail_w * 0.20, avail_w * 0.80]
    ext_col_w = [avail_w * 0.35, avail_w * 0.65]

    base_style = TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 1),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 1),
        ("LEFTPADDING", (0, 0), (0, -1), 0),
        ("LEFTPADDING", (1, 0), (1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
    ])

    sorted_inc = sorted(included_pap, key=lambda p: (p.year or 0, p.authors or ""))
    for i, p in enumerate(sorted_inc):
        block = []

        # Paper title
        block.append(Paragraph(
            f"<b>[{_s(p.citekey)}]</b> — {_s(p.title)}", s_title))

        # Citation table
        cit_data = []
        for label, val in [("Authors", p.authors), ("Venue", p.venue),
                           ("Year", p.year), ("DOI", getattr(p, 'doi', None))]:
            if not val: continue
            cit_data.append([
                Paragraph(f"<b>{_s(label)}:</b>", s_label),
                Paragraph(_s(str(val)), s_value),
            ])
        qa_pct = avg_qa.get(p.id)
        if qa_pct is not None:
            lvl = ("High" if qa_pct >= project.qa_high_threshold
                   else "Medium" if qa_pct >= project.qa_medium_threshold else "Low")
            cit_data.append([
                Paragraph("<b>Overall Quality Score:</b>", s_label),
                Paragraph(f"{qa_pct:.0f}% ({lvl})", s_value),
            ])
        if cit_data:
            ct = Table(cit_data, colWidths=cit_col_w, hAlign='LEFT')
            ct.setStyle(base_style)
            block.append(ct)

        # Thin separator
        block.append(Spacer(1, 2*mm))
        block.append(HRFlowable(width="90%", thickness=0.15*mm,
                                color=rl_colors.Color(0.82, 0.84, 0.86),
                                spaceAfter=2*mm))

        # Extraction fields table
        vals = rec_map.get(p.id, {})
        ext_data = []
        for fn in all_fns:
            val = vals.get(fn, "")
            if not val: continue
            label = fl.get(fn, fn)
            ext_data.append([
                Paragraph(f"<b>{_s(label)}:</b>", s_label),
                Paragraph(_s(str(val)), s_value),
            ])
        if ext_data:
            et = Table(ext_data, colWidths=ext_col_w, hAlign='LEFT')
            et.setStyle(base_style)
            block.append(et)

        # Wrap entire paper block in KeepTogether to avoid mid-block page splits
        # (platypus will break to next page if block doesn't fit)
        story.append(KeepTogether(block))

        # Spacer + heavy rule between papers
        if i < len(sorted_inc) - 1:
            story.append(Spacer(1, 3*mm))
            story.append(HRFlowable(width="100%", thickness=0.3*mm,
                                    color=rl_colors.Color(0.82, 0.84, 0.86),
                                    spaceAfter=3*mm))

    # End note
    story.append(Spacer(1, 6*mm))
    story.append(HRFlowable(width="100%", thickness=0.3*mm,
                            color=rl_colors.Color(0.82, 0.84, 0.86), spaceAfter=3*mm))
    # no trailing footer — report ends after the last paper

    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)
    return buf.getvalue()


def _build_pdf(
    project, reviewers, inc_criteria, exc_criteria, qa_criteria,
    search_strings, papers, rev_decisions, final_decisions,
    conflict_log, qa_scores, ext_fields, ext_records,
    snow_iterations, taxonomy, now,
    db_links=None, prisma_svg=None,
):
    # ── Stats ────────────────────────────────────────────────────────────────
    # Partition papers by origin: database searches vs. snowballing iterations.
    # Snowballing papers have source "snowballing:<iteration_number>".
    db_papers   = [p for p in papers if not p.source.startswith("snowballing:")]
    snow_papers = [p for p in papers if p.source.startswith("snowballing:")]
    dupes       = sum(1 for p in db_papers if p.dedup_status.startswith("duplicate_of:"))
    after_dedup = len(db_papers) - dupes
    scr_inc_ids = {d.paper_id for d in final_decisions if d.phase=="screening" and d.decision=="I"}
    scr_exc_ids = {d.paper_id for d in final_decisions if d.phase=="screening" and d.decision=="E"}
    ft_inc_ids  = {d.paper_id for d in final_decisions if d.phase=="full-text" and d.decision=="I"}
    ft_exc_ids  = {d.paper_id for d in final_decisions if d.phase=="full-text" and d.decision=="E"}
    snow_ids     = {p.id for p in snow_papers}
    snow_inc_ids = {d.paper_id for d in final_decisions if d.decision=="I" and d.paper_id in snow_ids}
    # "Included" = full-text included from DB searches + included from snowballing
    included_ids = ft_inc_ids | snow_inc_ids
    included_pap = [p for p in papers if p.id in included_ids]

    # QA percentage per paper: sum of raw scores / max possible score * 100
    by_paper: dict[int, list] = defaultdict(list)
    for s in qa_scores: by_paper[s.paper_id].append(s)
    max_qa = sum(c.max_score for c in qa_criteria) or 1.0
    avg_qa = {pid: sum(sc.score for sc in scores if sc.score is not None)/max_qa*100 for pid,scores in by_paper.items()}

    scr_conf_res = sum(1 for c in conflict_log if c.phase=="screening" and c.resolved)
    scr_conf_opn = sum(1 for c in conflict_log if c.phase=="screening" and not c.resolved)
    ft_conf_res  = sum(1 for c in conflict_log if c.phase=="full-text" and c.resolved)
    ft_conf_opn  = sum(1 for c in conflict_log if c.phase=="full-text" and not c.resolved)
    res_disc = sum(1 for c in conflict_log if c.resolution_method=="discussion")
    res_arb  = sum(1 for c in conflict_log if c.resolution_method=="arbitration")

    # Cohen's kappa for first two reviewers (R1 vs R2) in each phase
    kappa_results = {}
    if len(reviewers) >= 2:
        for phase in ("screening","full-text"):
            r1,r2 = reviewers[0],reviewers[1]
            r1d = {str(d.paper_id):d.decision for d in rev_decisions if d.reviewer_id==r1.id and d.phase==phase}
            r2d = {str(d.paper_id):d.decision for d in rev_decisions if d.reviewer_id==r2.id and d.phase==phase}
            kr = calculate_kappa(r1d, r2d)
            if kr: kappa_results[phase] = {"result":kr, "r1_name":r1.name, "r2_name":r2.name}

    # Per-database search metrics (precision/recall/F1).
    # Precision = included_from_DB / total_results_from_DB (how selective was this DB?)
    # Recall    = included_from_DB / total_included        (what fraction did this DB contribute?)
    # When PaperDatabaseLink rows exist, a paper can be credited to multiple DBs
    # (it was found in more than one search). Without links, only the primary source counts.
    search_metrics = []
    total_included = len(included_ids)
    use_links = db_links is not None and len(db_links) > 0
    link_map: dict[str, set] = {}
    if use_links:
        for lnk in db_links: link_map.setdefault(_norm_db(lnk.db_name), set()).add(lnk.paper_id)
    db_rc: dict[str, int|None] = {}
    for ss in search_strings:
        if ss.db_name:
            cn = _norm_db(ss.db_name)
            if cn not in db_rc: db_rc[cn] = ss.results_count
    for cn, rc in db_rc.items():
        paps = [p for p in db_papers if _norm_db(p.source)==cn and p.dedup_status=="original"]
        imp = len(paps)
        inc = len(link_map.get(cn,set())&included_ids) if use_links else sum(1 for p in paps if p.id in included_ids)
        ret = rc if rc is not None else imp
        pr = inc/ret if ret>0 else 0.0; re = inc/total_included if total_included>0 else 0.0
        f1 = (2*pr*re/(pr+re)) if (pr+re)>0 else 0.0
        search_metrics.append({"db":cn,"results":ret,"imported":imp,"included":inc,"precision":pr,"recall":re,"f1":f1})
    search_metrics.sort(key=lambda x: x["db"])

    rec_map: dict[int, dict[str,str]] = defaultdict(dict)
    for r in ext_records: rec_map[r.paper_id][r.field_name] = r.field_value or ""
    tax_types = sorted({t.taxonomy_type for t in taxonomy}) if taxonomy else []
    non_tax_fields = [f for f in sorted(ext_fields, key=lambda x: x.sort_order) if f.field_name not in set(tax_types)]
    all_fns = []; seen_fn = set()
    for fn in tax_types + [f.field_name for f in non_tax_fields]:
        if fn not in seen_fn: seen_fn.add(fn); all_fns.append(fn)
    fl = {t: t.replace("_"," ").title() for t in tax_types}
    fl.update({f.field_name: f.field_label for f in ext_fields})

    # ── PDF ──────────────────────────────────────────────────────────────────
    pdf = _Report(project.title)
    pdf.add_page()

    # ═══ COVER PAGE ══════════════════════════════════════════════════════════
    pdf.ln(55)
    pdf.set_font("Times","B",20); pdf.set_text_color(*_BLACK)
    pdf.multi_cell(_CW, 10, _s(project.title), align="C")
    pdf.ln(4)
    pdf.set_font("Times","",10); pdf.set_text_color(*_DARK)
    pdf.cell(0,5,"Supplementary Material: Search Protocol & Results",align="C",ln=True)
    pdf.ln(3)
    pdf.set_font("Times","",9)
    pdf.cell(0,4,now,align="C",ln=True)
    pdf.ln(3)
    # Horizontal rule
    pdf.set_draw_color(*_BORDER); pdf.set_line_width(0.2)
    pdf.line(70, pdf.get_y(), 140, pdf.get_y()); pdf.ln(3)
    # Reviewer count
    pdf.set_font("Times","",9); pdf.set_text_color(*_DARK)
    pdf.cell(0,4,f"{len(reviewers)} reviewer{'s' if len(reviewers)!=1 else ''}",align="C",ln=True)
    # Citation
    pdf.ln(2); pdf.set_font("Times","I",7); pdf.set_text_color(*_GRAY_LT)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(_CW, 3.5,
        "Generated with ReviQ. If you use ReviQ in your research, please cite: "
        "Haindl, Philipp (submitted). ReviQ: A Systematic Literature Review Workbench. SoftwareX.",
        align="C")
    pdf.set_text_color(*_BLACK)

    pdf._is_cover = False
    sn = 0   # section counter — increments only when a section is actually emitted
    prisma_insert_page = None

    # ═══ 1. RESEARCH PROTOCOL ═══════════════════════════════════════════════
    sn += 1; pdf.add_page()
    pdf.h2(f"{sn}. Research Protocol")
    if project.description:
        pdf.h3("Research Question / Scope"); pdf.body(project.description)
    def _ct(crit, title):
        if not crit: return
        pdf.h3(title)
        pdf.wrapping_table([("Label",0.10),("Phase",0.18),("Description",0.72)],
                           [[c.label, c.phase.replace("-"," ").title(), c.description] for c in crit])
    _ct(inc_criteria, "Inclusion Criteria"); _ct(exc_criteria, "Exclusion Criteria")
    if qa_criteria:
        pdf.h3("Quality Assessment Criteria")
        pdf.wrapping_table([("Label",0.12),("Description",0.70),("Max Score",0.18)],
                           [[c.label, c.description, c.max_score] for c in qa_criteria])
        pdf.note(f"Quality thresholds: High >= {project.qa_high_threshold}%, Medium >= {project.qa_medium_threshold}%")

    # ═══ 2. SEARCH STRATEGY ═════════════════════════════════════════════════
    sn += 1
    pdf.h2(f"{sn}. Search Strategy")
    if search_strings:
        for ss in search_strings:
            pdf.h3(f"Database: {_db_name(_norm_db(ss.db_name))}")
            kvs = []
            if ss.search_date: kvs.append(("Search Date", _s(ss.search_date)))
            if ss.filter_settings:
                kvs.append(("Filters", _s(ss.filter_settings).replace("Confererence","Conference")))
            if ss.results_count is not None: kvs.append(("Results Count", f"{ss.results_count:,}"))
            if kvs: pdf.kv_table(kvs, 0.25)
            if ss.query_string:
                pdf.set_font("Courier","",7); pdf.set_fill_color(*_GRAY_BG)
                pdf.set_x(pdf.l_margin+2)
                pdf.multi_cell(_CW-4, 3.5, _s(ss.query_string,500), fill=True)
                pdf.set_fill_color(*_WHITE); pdf.ln(2); pdf.set_font("Times","",9)
    else:
        pdf.body("No search strings recorded.")

    # ═══ 3. PRISMA 2020 FLOW DIAGRAM ════════════════════════════════════════
    sn += 1
    pdf.h2(f"{sn}. PRISMA 2020 Flow Diagram")
    if prisma_svg:
        # Record page number — we'll insert the vector PRISMA page after merging
        prisma_insert_page = pdf.page_no()
        pdf.note("See PRISMA flow diagram on the following page.")
    else:
        pdf.note("PRISMA flow diagram not available. To include it, visit the PRISMA tab before downloading the PDF.")

    # ═══ 4. SEARCH DATABASE METRICS ═════════════════════════════════════════
    if search_metrics:
        sn += 1
        pdf.h2(f"{sn}. Search Database Metrics")
        pdf.note("Precision = included / DB results  |  Recall = included from DB / total included  |  F1 = harmonic mean")
        pdf.wrapping_table(
            [("Database",0.22),("DB Results",0.13),("Imported",0.13),("Included",0.13),("Precision",0.13),("Recall",0.13),("F1",0.13)],
            [[_db_name(m["db"]),f'{m["results"]:,}',m["imported"],m["included"],
              f'{m["precision"]*100:.1f}%',f'{m["recall"]*100:.1f}%',f'{m["f1"]*100:.1f}%'] for m in search_metrics])

    # ═══ 5. SCREENING & SELECTION STATISTICS ═════════════════════════════════
    sn += 1
    pdf.h2(f"{sn}. Screening & Selection Statistics")
    pdf.kv_table([
        ("Total records retrieved (all sources)", f"{len(papers):,}"),
        ("Duplicates removed", f"{dupes:,}"),
        ("Records after deduplication", f"{after_dedup:,}"),
        ("Excluded at title/abstract screening", f"{len(scr_exc_ids):,}"),
        ("Included at screening (to full-text)", f"{len(scr_inc_ids):,}"),
        ("Excluded at full-text eligibility", f"{len(ft_exc_ids):,}"),
        ("Included from database searches", f"{len(ft_inc_ids):,}"),
        ("Included from snowballing", f"{len(snow_inc_ids):,}"),
        ("Total included studies", f"{len(included_ids):,}"),
    ], 0.60)
    pdf.note(
        "Note: 'Included from database searches' and 'Included from snowballing' are not additive; "
        "snowballed papers were assessed separately and the total of "
        f"{len(included_ids)} studies represents the combined non-overlapping set.")
    if conflict_log:
        pdf.h3("Conflict Resolution")
        pdf.kv_table([
            ("Screening conflicts (resolved)", f"{scr_conf_res:,}"),
            ("Screening conflicts (open)", f"{scr_conf_opn:,}"),
            ("Full-text conflicts (resolved)", f"{ft_conf_res:,}"),
            ("Full-text conflicts (open)", f"{ft_conf_opn:,}"),
            ("Resolved by discussion", f"{res_disc:,}"),
            ("Resolved by arbitration", f"{res_arb:,}"),
        ], 0.60)

    # ═══ 6. INTER-RATER AGREEMENT ═══════════════════════════════════════════
    if kappa_results:
        sn += 1
        pdf.h2(f"{sn}. Inter-Rater Agreement")
        for phase, data in kappa_results.items():
            kr = data["result"]; pl = phase.replace("-"," ").title()
            pdf.h3(f"{pl} - {_s(data['r1_name'])} vs. {_s(data['r2_name'])}")
            pdf.kv_table([
                ("Cohen's k", f"{kr.kappa:.4f}"),
                ("95% CI", f"[{kr.kappa_ci_lower:.4f}, {kr.kappa_ci_upper:.4f}]"),
                ("PABAK", f"{kr.pabak:.4f}"),
                ("Observed agreement (Po)", f"{kr.observed_agreement:.4f}"),
                ("Interpretation", kr.interpretation),
                ("Papers in sample", f"{kr.n_papers:,}"),
                ("Both Include", f"{kr.n_agree_include:,}"),
                ("Both Exclude", f"{kr.n_agree_exclude:,}"),
                ("Disagreements", f"{kr.n_disagree:,}"),
            ], 0.45)
        pdf.note(
            "Interpretation follows Landis, J.R. & Koch, G.G. (1977). The measurement of observer "
            "agreement for categorical data. Biometrics, 33(1), 159-174. PABAK adjusts for prevalence "
            "and bias: Byrt, T., Bishop, J., & Carlin, J.B. (1993). Bias, prevalence and kappa. "
            "Journal of Clinical Epidemiology, 46(5), 423-429.")

    # ═══ 7. QUALITY ASSESSMENT ═══════════════════════════════════════════════
    if qa_criteria:
        sn += 1
        pdf.h2(f"{sn}. Quality Assessment Results")
        qa_included = {pid: pct for pid, pct in avg_qa.items() if pid in included_ids}
        if qa_included:
            high = sum(1 for v in qa_included.values() if v>=project.qa_high_threshold)
            med  = sum(1 for v in qa_included.values() if project.qa_medium_threshold<=v<project.qa_high_threshold)
            low  = sum(1 for v in qa_included.values() if v<project.qa_medium_threshold)
            avg_all = sum(qa_included.values())/len(qa_included)
            pdf.kv_table([
                ("Papers assessed",f"{len(qa_included):,}"),("Average QA score",f"{avg_all:.1f}%"),
                ("High quality",f"{high:,}"),("Medium quality",f"{med:,}"),("Low quality",f"{low:,}"),
            ], 0.45)
            extra = len(avg_qa) - len(qa_included)
            if extra > 0:
                pdf.note(f"{extra} additional candidate(s) underwent QA assessment before being excluded "
                         f"at full-text stage; they are not counted in the {len(included_ids)} included studies.")
            qa_paps = sorted([p for p in included_pap if p.id in qa_included], key=lambda p: qa_included.get(p.id,0), reverse=True)
            if qa_paps:
                pdf.h3("Per-Paper Quality Scores")
                cc = [(c.label,0.06) for c in qa_criteria]
                bc = [("Paper Key",0.14),("Year",0.06)]; ec = [("Total",0.08),("Level",0.08)]
                fixed = sum(f for _,f in bc+ec)
                avail_frac = 1.0 - fixed
                cc = [(c.label, avail_frac/len(qa_criteria)) for c in qa_criteria]
                pdf.wrapping_table(bc+cc+ec,
                    [[f"[{p.citekey}]", p.year or "-"]
                     + [next((str(s.score) for s in by_paper.get(p.id,[]) if s.criterion_id==c.id and s.score is not None),"-") for c in qa_criteria]
                     + [f"{qa_included.get(p.id,0):.0f}%",
                        "High" if qa_included.get(p.id,0)>=project.qa_high_threshold else "Med" if qa_included.get(p.id,0)>=project.qa_medium_threshold else "Low"]
                     for p in qa_paps])

    # ═══ 8. SNOWBALLING ═════════════════════════════════════════════════════
    if snow_iterations:
        sn += 1
        pdf.h2(f"{sn}. Snowballing Iterations")
        rows = []
        for it in sorted(snow_iterations, key=lambda x: x.iteration_number):
            ip = [p for p in snow_papers if p.source==f"snowballing:{it.iteration_number}"]
            rows.append([f"Iteration {it.iteration_number}", it.iteration_type.title(), len(ip),
                         sum(1 for p in ip if p.id in included_ids), "Yes" if it.saturation_confirmed else "No"])
        pdf.wrapping_table([("Iteration",0.22),("Type",0.18),("Retrieved",0.20),("Included",0.20),("Saturated",0.20)], rows)

    # ═══ 9. DATA EXTRACTION SCHEMA ══════════════════════════════════════════
    sn += 1
    pdf.h2(f"{sn}. Data Extraction Schema")

    if taxonomy:
        pdf.h3("Taxonomy Categories")
        tax_sorted = sorted(taxonomy, key=lambda t: (t.taxonomy_type, t.sort_order))
        for tt, entries in groupby(tax_sorted, key=lambda t: t.taxonomy_type):
            lbl = tt.replace("_"," ").title()
            vals = ", ".join(_s(e.value) for e in entries)
            pdf.h4(f"{_s(lbl)}:")
            pdf.indent_text(vals, indent=12)

    if non_tax_fields:
        pdf.h3("Custom Extraction Fields")
        for f in non_tax_fields:
            tm = {"text":"Free text","number":"Number","boolean":"Boolean - Yes / No","dropdown":"Select"}
            tl = tm.get(f.field_type, f.field_type)
            if f.field_type == "dropdown" and f.options:
                try: tl += " - " + " / ".join(str(o) for o in json.loads(f.options))
                except: tl += " - " + str(f.options)
            pdf.h4(_s(f.field_label))
            pdf.indent_text(f"Type: {_s(tl, 200)}", indent=12)

    # Sections 1-9 complete. Output the fpdf2 PDF.
    main_bytes = bytes(pdf.output())

    # Merge PRISMA vector PDF if available
    if prisma_svg and prisma_insert_page:
        main_bytes = _merge_prisma_pdf(main_bytes, prisma_svg, prisma_insert_page)

    # ═══ 10. INCLUDED PAPERS (built with ReportLab Platypus) ════════════════
    sn += 1
    if included_pap:
        sec10_bytes = _build_section10_pdf(
            included_pap, avg_qa, project, all_fns, fl, rec_map,
            section_num=sn, slr_title=project.title,
        )
        # Append Section 10 PDF pages to the main PDF
        try:
            from pypdf import PdfReader, PdfWriter
            writer = PdfWriter()
            for page in PdfReader(io.BytesIO(main_bytes)).pages:
                writer.add_page(page)
            for page in PdfReader(io.BytesIO(sec10_bytes)).pages:
                writer.add_page(page)
            buf = io.BytesIO()
            writer.write(buf)
            main_bytes = buf.getvalue()
        except ImportError:
            pass  # pypdf not available — Section 10 skipped

    return main_bytes


# ─────────────────────────────────────────────────────────────────────────────

def _generate(pid, session, prisma_svg=None):
    project = session.get(Project, pid)
    if not project: raise HTTPException(404, "Project not found")
    def q(m): return session.exec(select(m).where(m.project_id == pid)).all()
    now = datetime.utcnow().strftime("%B %d, %Y")
    buf = io.BytesIO(_build_pdf(
        project, q(Reviewer), q(InclusionCriterion), q(ExclusionCriterion), q(QACriterion),
        q(DatabaseSearchString), q(Paper), q(ReviewerDecision), q(FinalDecision),
        q(ConflictLog), q(QAScore), q(ExtractionField), q(ExtractionRecord),
        q(SnowballingIteration), q(TaxonomyEntry), now,
        db_links=q(PaperDatabaseLink), prisma_svg=prisma_svg))
    safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in project.title)
    return StreamingResponse(buf, media_type="application/pdf",
                             headers={"Content-Disposition": f'attachment; filename="reviq_protocol_{safe}.pdf"'})


@router.post("/{pid}/report/pdf")
def download_report_post(pid: int, body: ReportBody, session: Session = Depends(get_session)):
    return _generate(pid, session, prisma_svg=body.prisma_svg)

@router.get("/{pid}/report/pdf")
def download_report_get(pid: int, session: Session = Depends(get_session)):
    return _generate(pid, session)
