/**
 * Donut chart — static SVG embedded via dangerouslySetInnerHTML.
 *
 * The SVG string is produced by generateDonutSvgString (donutSvg.ts).
 * All donuts use a fixed-size viewBox (FIXED_VIEW_PAD) so the ring
 * always appears at the same scale regardless of label count or length.
 */
import { useMemo } from 'react'

import type { CategoryCount } from '../../utils/charts'
import { COLORS } from './tokens'
import { generateDonutSvgString } from './donutSvg'

interface Props {
  data:       CategoryCount[]
  accent?:    string
  ariaLabel?: string
  svgId?:     string
  /** Unused — kept for call-site compatibility. */
  unit?:      string
}

export function Donut({
  data,
  accent    = COLORS.accent,
  ariaLabel = 'Donut chart',
  svgId,
}: Props) {
  const svgString = useMemo(
    () => generateDonutSvgString(data, accent, ariaLabel, svgId),
    [data, accent, ariaLabel, svgId],
  )
  // dangerouslySetInnerHTML is safe here: SVG is generated by our own pure
  // function from trusted internal data, never from user-supplied HTML.
  // max-width caps the SVG at a sensible display size so the card body
  // doesn't grow as tall as the card width.  margin:auto centres the SVG
  // horizontally when the card is wider than max-width.
  return (
    <div style={{ maxWidth: '450px', margin: '0 auto' }}
         dangerouslySetInnerHTML={{ __html: svgString }} />
  )
}
