"""Figure description via a vision model.

**What this produces is model output, not source content.** A description here
is evidence *about* a figure, generated by a named model from archived bytes at
a recorded time. It must never be merged into extracted text or quoted as if
the source had written it — see the comment on `figure_descriptions` in
schema.sql, which is the load-bearing part of this feature.

Three properties make a generated description defensible in a review:

  * **The input is archived.** The figure bytes live in the run's WARC, so any
    description can be re-generated, compared against a different model, or
    checked by eye.
  * **The generator is recorded.** Exact model id, verbatim prompt, timestamp
    and token counts are stored with every description.
  * **It is versioned, not overwritten.** Re-describing with a different model
    or a revised prompt adds a row; the old description stays.

Opt-in, behind its own extra and its own flag, because it is the one part of
this tool that sends content to a third party and costs money per item.
"""

from __future__ import annotations

import base64
from dataclasses import dataclass

# Cheapest current model with vision. The user chooses the tier: describing a
# few hundred figures should cost a euro or two, not fifty.
DEFAULT_MODEL = "claude-haiku-4-5"

# Kept short on purpose — a description is a caption, not an essay.
MAX_TOKENS = 600

# Stored verbatim with every description, so a reader can judge what the model
# was asked for. Changing it creates new descriptions rather than replacing the
# old ones (see the UNIQUE constraint in schema.sql).
#
# Written to constrain the model to the observable: a review cannot use
# "this figure suggests organisations should..." as evidence, but it can use
# "five levels labelled Initial, Managed, Defined, Quantified, Optimising".
DEFAULT_PROMPT = (
    "Describe this figure factually, completely enough that someone who cannot see "
    "it could cite it. Report only what is visible: the kind of figure, its title "
    "or caption if shown, axis and column labels, the named levels, stages or "
    "dimensions it contains, and any explicit values or numbers. Do not interpret, "
    "do not generalise beyond what is shown, and do not add background knowledge. "
    "If the image carries no substantive information — a logo, an icon, decoration, "
    "a stock photograph, a portrait — reply with exactly: NO SUBSTANTIVE CONTENT."
)

# The sentinel the prompt asks for, so non-figures are filterable in SQL.
NO_CONTENT = "NO SUBSTANTIVE CONTENT"


@dataclass
class Description:
    model: str
    prompt: str
    description: str | None = None
    input_tokens: int | None = None
    output_tokens: int | None = None
    error: str | None = None

    @property
    def is_substantive(self) -> bool:
        return bool(self.description) and NO_CONTENT not in self.description


def describe_figure(
    content: bytes,
    media_type: str,
    *,
    model: str = DEFAULT_MODEL,
    prompt: str = DEFAULT_PROMPT,
    client=None,
) -> Description:
    """Describe one figure. Never raises — a failure is a recorded outcome."""
    try:
        import anthropic
    except ImportError:
        return Description(
            model=model, prompt=prompt,
            error="anthropic not installed; pip install -r requirements-optional.txt",
        )

    if client is None:
        try:
            client = anthropic.Anthropic()
        except Exception as exc:
            return Description(
                model=model, prompt=prompt,
                error=f"could not create client ({exc}); is ANTHROPIC_API_KEY set?",
            )

    try:
        response = client.messages.create(
            model=model,
            max_tokens=MAX_TOKENS,
            messages=[{
                "role": "user",
                "content": [
                    {
                        "type": "image",
                        "source": {
                            "type": "base64",
                            "media_type": media_type,
                            "data": base64.standard_b64encode(content).decode("ascii"),
                        },
                    },
                    {"type": "text", "text": prompt},
                ],
            }],
        )
    except Exception as exc:
        return Description(model=model, prompt=prompt, error=f"{type(exc).__name__}: {exc}")

    text = "".join(
        block.text for block in response.content if getattr(block, "type", None) == "text"
    ).strip()
    usage = getattr(response, "usage", None)
    return Description(
        model=getattr(response, "model", model),
        prompt=prompt,
        description=text or None,
        input_tokens=getattr(usage, "input_tokens", None),
        output_tokens=getattr(usage, "output_tokens", None),
        error=None if text else "model returned no text",
    )
